server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Seoul
    username: oauth
    password: 1234

custom:
  jwt:
    trusted-issuerUri:
      - http://127.0.0.1:9000
      - http://127.0.0.1:9001