server:
  port: 9001

spring:
  profiles:
    include: oauth2, data

authorization-server:
  jwks-uri: http://127.0.0.1:9001/oauth2/jwks
  issuer-uri: http://127.0.0.1:9001

token:
  issuer: http://127.0.0.1:9001
  audience: http://127.0.0.1:8081
  exp: 15
  refresh:
    exp: 20040

logging:
  level:
    sql: debug

